# Generated by Django 5.1.5 on 2025-02-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userflashcard',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
